### ISSUE TITLE
Protocol version 32 is not supported yet by this client.

### ISSUE THREAD

**Issue by zero-** [orientechnologies/pyorient#9] opened 2015-11-17 19:19 UTC
Getting `Protocol version 32 is not supported yet by this client.` and I'm running 2.1.5.

Any ETA support for newer protocols?

**Comment by lashex** [comment] 2015-12-30 19:39
I just started trying to poke around with OrientDB and I am also getting this when running 2.1.8. Specifically, `pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 32 is not supported yet` by this client.

**Comment by Ostico** [comment] 2015-12-30 21:50
Hi guys, protocol 32 is already supported by pyorient. 

The issue is in the pypi repository.

I apologize for this. Please, for now clone the github repository untill pypi will be fixed.

It works.

**Closed** 2016-06-06 23:21 UTC
